### ISSUE TITLE
UWP app doesn't auto-launch

### ISSUE THREAD

**Issue by jhuynh405** [JakubSteplowski/SpotifyLyricsNET#12] opened 2020-06-16 16:34 UTC
Doesn't auto-launch. Tried resetting computer after installation, as well as closing Spotify & reopening. Tried manually launching from start menu, and it opens a blank window, then closes.

**Comment by JakubSteplowski** [comment] 2020-06-16 16:39
The issue is caused by your antivirus, check #7 to understand why.

Duplicate of #13

**Closed by JakubSteplowski** 2020-06-16 16:39 UTC
